language: python
python:
    - 3.5
    - 3.6
    - 3.7
os:
    - linux
dist:
    - xenial
before_install:
    - sudo apt update
    - sudo apt install graphviz graphviz-dev pandoc
install:
    - pip3 install -r requirements.txt
script:
- make
